
export const MODE_USER_LOGIN='MODE_USER_LOGIN';
export const MODE_USER_REGISTER='MODE_USER_REGISTER';


export const ACTION_LOGIN='ACTION_LOGIN';
export const ACTION_LOGOUT='ACTION_LOGOUT';
export const ACTION_REGISTER='ACTION_REGISTER';

export const ACTION_BOOK_FETCH='ACTION_BOOK_FETCH';
export const ACTION_BOOK_SELECT='ACTION_BOOK_SELECT';
export const ACTION_BOOK_DELETE='ACTION_BOOK_DELETE';
export const ACTION_BOOK_ADD='ACTION_BOOK_ADD';


export const ACTION_BOOK_SELECT_DONE='ACTION_BOOK_SELECT_DONE';
export const ACTION_STATUS_SET='ACTION_STATUS_SET';

export const STATUS_DONE='STATUS_DONE';
export const STATUS_PENDING='STATUS_PENDING';
export const STATUS_ERROR='STATUS_ERROR';




